name: Hello # workflow name

on: push # ivent プッシュ時に起動

jobs: # jobの定義
  hello: # jobID
    runs-on: ubuntu-latest # runner
    steps: # ステップの定義
      - run: echo "Hello, world" # シェルコマンドの実行
      - uses: actions/checkout@v4 # アクションの呼び出し


